import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "carbon-surface": "#141416",
        "gold-deep": "#8F6B27",
        "inverse-on-surface": "#313031",
        "on-primary": "#422d00",
        "secondary-fixed": "#ffe088",
        "outline-variant": "#4e4638",
        "surface-container-low": "#1c1b1c",
        "on-secondary": "#3c2f00",
        "on-primary-container": "#4c3400",
        "tertiary-fixed": "#ffdeac",
        "secondary-container": "#af8d11",
        "primary-container": "#c59b4e",
        "surface-container-highest": "#353436",
        "on-primary-fixed-variant": "#5e4200",
        "gold-border": "#C59B4E33",
        tertiary: "#f1be69",
        "surface-bright": "#39393a",
        "on-tertiary": "#432c00",
        "on-secondary-fixed": "#241a00",
        "primary-fixed": "#ffdea8",
        "on-tertiary-fixed-variant": "#5f4100",
        "on-surface-variant": "#d2c5b3",
        "whatsapp-green": "#25D366",
        "surface-container-high": "#2a2a2b",
        "text-muted": "#A1A1AA",
        "on-error-container": "#ffdad6",
        outline: "#9b8f7f",
        "primary-fixed-dim": "#edc06f",
        secondary: "#e9c349",
        "surface-container-lowest": "#0e0e0f",
        "on-tertiary-container": "#4d3400",
        "on-error": "#690005",
        "surface-container": "#201f20",
        "on-surface": "#e5e2e3",
        error: "#ffb4ab",
        "gold-light": "#F2D07E",
        "carbon-elevated": "#1B1B1F",
        "on-secondary-fixed-variant": "#574500",
        surface: "#131314",
        "inverse-surface": "#e5e2e3",
        "inverse-primary": "#7a580f",
        "tertiary-fixed-dim": "#f1be69",
        "secondary-fixed-dim": "#e9c349",
        primary: "#edc06f",
        "carbon-void": "#070707",
        "surface-variant": "#353436",
        "text-primary": "#F7F7F8",
        "surface-tint": "#edc06f",
        "surface-dim": "#131314",
        "on-tertiary-fixed": "#281900",
        "on-secondary-container": "#342800",
        "tertiary-container": "#c99a48",
        "on-primary-fixed": "#271900",
        background: "#131314",
        "error-container": "#93000a",
        "on-background": "#e5e2e3"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        margin: "2rem",
        "margin-mobile": "1.25rem",
        "space-xl": "2.5rem",
        gutter: "1rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "gutter-mobile": "0.75rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "headline-xl": ["var(--font-montserrat)", "sans-serif"],
        "body-sm": ["var(--font-montserrat)", "sans-serif"],
        "headline-lg": ["var(--font-montserrat)", "sans-serif"],
        "body-lg": ["var(--font-montserrat)", "sans-serif"],
        "headline-md": ["var(--font-montserrat)", "sans-serif"],
        "body-md": ["var(--font-montserrat)", "sans-serif"],
        "headline-xl-mobile": ["var(--font-montserrat)", "sans-serif"],
        "label-sm": ["var(--font-montserrat)", "sans-serif"],
        "label-md": ["var(--font-montserrat)", "sans-serif"],
        "title-lg": ["var(--font-montserrat)", "sans-serif"],
        "title-md": ["var(--font-montserrat)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-montserrat)", "sans-serif"],
        "label-lg": ["var(--font-montserrat)", "sans-serif"]
      },
      fontSize: {
        "display-large": ["clamp(4rem, 10vw, 9.5rem)", { lineHeight: "0.85", letterSpacing: "-0.04em", fontWeight: "900" }],
        "headline-xl": ["clamp(2.5rem, 5vw, 4.5rem)", { lineHeight: "1.1", letterSpacing: "0.01em", fontWeight: "700" }],
        "headline-lg": ["clamp(2rem, 4vw, 3.5rem)", { lineHeight: "1.15", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["clamp(1.5rem, 3vw, 2.25rem)", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "title-lg": ["clamp(1.25rem, 2vw, 1.5rem)", { lineHeight: "1.3", letterSpacing: "0.08em", fontWeight: "700" }],
        "title-md": ["clamp(1.125rem, 1.5vw, 1.25rem)", { lineHeight: "1.4", letterSpacing: "0.06em", fontWeight: "600" }],
        "body-lg": ["clamp(1.125rem, 1.5vw, 1.25rem)", { lineHeight: "1.6", fontWeight: "300" }],
        "body-md": ["clamp(1rem, 1.2vw, 1.125rem)", { lineHeight: "1.5", fontWeight: "300" }],
        "body-sm": ["clamp(0.875rem, 1vw, 1rem)", { lineHeight: "1.5", fontWeight: "300" }],
        "label-lg": ["clamp(0.875rem, 1vw, 1rem)", { lineHeight: "1.2", letterSpacing: "0.12em", fontWeight: "700" }],
        "label-md": ["clamp(0.75rem, 0.8vw, 0.875rem)", { lineHeight: "1.2", letterSpacing: "0.14em", fontWeight: "600" }],
        "label-sm": ["clamp(0.625rem, 0.7vw, 0.75rem)", { lineHeight: "1.2", letterSpacing: "0.2em", fontWeight: "700" }],
        "micro": ["clamp(0.5rem, 0.6vw, 0.625rem)", { lineHeight: "1.2", letterSpacing: "0.25em", fontWeight: "700" }],
      }
    }
  }
};

export default config;
